# Auto-generated by ma-provider-tools — do not edit manually.
# conftest.py — make provider/ importable as music_assistant.providers.dlna_receiver
import importlib
import pathlib
import types
import sys

_repo = pathlib.Path(__file__).resolve().parent

# Build namespace package chain: music_assistant -> music_assistant.providers
for _pkg in ("music_assistant", "music_assistant.providers"):
    if _pkg not in sys.modules:
        mod = types.ModuleType(_pkg)
        mod.__path__ = []  # type: ignore[attr-defined]
        mod.__package__ = _pkg
        sys.modules[_pkg] = mod

# Point music_assistant.providers.dlna_receiver at ./provider/
_target = str(_repo / "provider")
_fqn = "music_assistant.providers.dlna_receiver"
spec = importlib.util.spec_from_file_location(
    _fqn,
    _repo / "provider" / "__init__.py",
    submodule_search_locations=[_target],
)
_mod = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
sys.modules[_fqn] = _mod
spec.loader.exec_module(_mod)  # type: ignore[union-attr]
