#!/bin/sh
# Init script for DLNA Receiver provider Docker dev environment.
# Auto-generated by ma-provider-tools — do not edit manually.
set -e

echo "==> Setting up DLNA Receiver provider..."

# Locate MA providers directory inside the container venv
PROVIDERS_DIR=$(/app/venv/bin/python3 -c \
    "import music_assistant.providers, os; print(os.path.dirname(music_assistant.providers.__file__))")

# Remove any existing yandex_music provider (image may bundle one), then symlink ours
rm -rf "${PROVIDERS_DIR}/dlna_receiver"
ln -s /tmp/provider "${PROVIDERS_DIR}/dlna_receiver"
echo "==> Provider linked: ${PROVIDERS_DIR}/dlna_receiver"

# Install provider-specific runtime dependencies (skips music_assistant itself)
DEPS=$(/app/venv/bin/python3 - <<'PYEOF'
import sys
try:
    import tomllib
except ImportError:
    import tomli as tomllib
try:
    with open("/tmp/pyproject.toml", "rb") as f:
        data = tomllib.load(f)
    deps = [
        d for d in data.get("project", {}).get("dependencies", [])
        if not d.lower().startswith("music_assistant")
    ]
    print(" ".join(deps))
except Exception:
    pass
PYEOF
)
if [ -n "$DEPS" ]; then
    echo "==> Installing provider dependencies: $DEPS"
    /app/venv/bin/pip install --quiet $DEPS
fi

echo "==> Starting Music Assistant..."
exec /usr/local/bin/entrypoint.sh --data-dir /data --cache-dir /data/.cache
